-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 17:27:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cloudDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cloudDB` ;

-- -----------------------------------------------------
-- Schema cloudDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cloudDB` DEFAULT CHARACTER SET latin1 ;
USE `cloudDB` ;

-- -----------------------------------------------------
-- Table `cloudDB`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cloudDB`.`addresses` ;

CREATE TABLE IF NOT EXISTS `cloudDB`.`addresses` (
  `add_id` INT NOT NULL,
  `add_street` VARCHAR(45) NULL,
  `add_city` VARCHAR(45) NULL,
  `add_country` VARCHAR(45) NULL,
  PRIMARY KEY (`add_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cloudDB`.`users` ;

CREATE TABLE IF NOT EXISTS `cloudDB`.`users` (
  `use_id` INT NOT NULL AUTO_INCREMENT,
  `use_username` VARCHAR(45) NOT NULL,
  `use_firstname` VARCHAR(45) NULL,
  `use_lastname` VARCHAR(45) NULL,
  `use_password` VARCHAR(45) NULL,
  `use_email` VARCHAR(45) NULL,
  `use_created` TIMESTAMP NULL,
  `use_billing_add` INT NOT NULL,
  `use_delivery_add` INT NOT NULL,
  `use_sex` CHAR(1) NOT NULL,
  PRIMARY KEY (`use_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudDB`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cloudDB`.`subscriptions` ;

CREATE TABLE IF NOT EXISTS `cloudDB`.`subscriptions` (
  `sub_id` INT NOT NULL,
  `sub_name` VARCHAR(45) NULL,
  `sub_price` VARCHAR(45) NULL,
  `sub_description` VARCHAR(45) NULL,
  PRIMARY KEY (`sub_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cloudDB`.`user_subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cloudDB`.`user_subscriptions` ;

CREATE TABLE IF NOT EXISTS `cloudDB`.`user_subscriptions` (
  `usu_username` VARCHAR(45) NOT NULL,
  `usu_sub_id` INT NOT NULL,
  `usu_created` TIMESTAMP NULL,
  PRIMARY KEY (`usu_username`, `usu_sub_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
